Add support for set values
toumorokoshi/deepmerge pull request #11
Opened 2021-04-16 15:40 UTC by ThePletch

Introduces simple merge strategies for sets, defaulting to merging them by union.

2021-04-18 13:50 UTC, toumorokoshi requested changes
Thanks for the PR! The overall change makes sense. A couple notes:

- looks like the set.py file was not added, which is also causing the CI to fail. could you add that in?
- could you add unit tests as to the expected behavior of set merging, as well as a unit test to verify the behavior of  the default mergers?

Thanks again!

2021-04-18 15:00 UTC, ThePletch commented on deepmerge/__init__.py
> -from .strategy.core import STRATEGY_END
oh huh, how'd this get deleted?

2021-04-18 15:06 UTC, ThePletch commented
is it alright if i drop the python 2.7 and pypy builds from the travis config, or are you still looking to maintain python 2.7 support? it looks like they're failing due to unrelated dependency issues.

2021-04-25 20:14 UTC, toumorokoshi commented
> is it alright if i drop the python 2.7 and pypy builds from the travis config, or are you still looking to maintain python 2.7 support? it looks like they're failing due to unrelated dependency issues.

I think that's fine, although that may also require changing the pypy env to pypy3. 

If it's fairly clear to you on how to make that change, go for it. I might just try it now too.

2021-04-25 20:26 UTC, toumorokoshi commented
> > is it alright if i drop the python 2.7 and pypy builds from the travis config, or are you still looking to maintain python 2.7 support? it looks like they're failing due to unrelated dependency issues.
> 
> I think that's fine, although that may also require changing the pypy env to pypy3.
> 
> If it's fairly clear to you on how to make that change, go for it. I might just try it now too.

okay fixed in #12. If you rebase it should it fix your build.

2021-04-25 20:31 UTC, merged

2021-04-25 20:31 UTC, toumorokoshi commented
LGTM, thanks!

2021-04-25 20:36 UTC, toumorokoshi commented
shipped as [0.3.0](https://pypi.org/project/deepmerge/0.3.0/), thanks again!