Include data in `InvalidMerge` exception class
toumorokoshi/deepmerge pull request #9
Opened 2021-02-14 00:46 UTC by alexreg

This allows for programmatic access to the data reflected by an `InvalidMerge` exception, and not just a string representation (though this is preserved too).

2021-02-26 16:58 UTC, toumorokoshi requested changes
Thank you for the change! Can you add a unit test so we can ensure those fields are not removed accidentally?

I think [this](https://github.com/toumorokoshi/deepmerge/blob/master/deepmerge/tests/test_full.py#L32) is the right place to add such a test.

2021-02-26 20:00 UTC, alexreg commented
@toumorokoshi Sure, I'll do that a bit later.

2021-02-26 22:51 UTC, alexreg commented
Done! Hope that looks okay to you. (And if you don't mind making a 0.2 release on pip maybe, that would be appreciated.)

2021-02-27 15:16 UTC, alexreg commented
Ah, I see it's the Python 2.7 build failing. Is there any particular reason you're still supporting it, now that it's (well) past end-of-lifetime?

2021-03-10 06:10 UTC, toumorokoshi commented on deepmerge/tests/test_full.py
> +    with pytest.raises(InvalidMerge, match=r"^no more strategies found for type conflict and arguments \(<deepmerge.merger.Merger object at 0x[0-9a-f]+>, \['foo'\], 0, 'a string!'\), {}$") as exc_inf
probably no need for the verbose regex. In my experience trying verify things like formatting of error messages ends up being very brittle. 

Using the Exception type to state the category, and verifying that is sufficient.

2021-03-10 06:12 UTC, toumorokoshi commented
> Ah, I see it's the Python 2.7 build failing. Is there any particular reason you're still supporting it, now that it's (well) past end-of-lifetime?

no, it's fine to do so. That said the fix for python2.7 looks trivial (adding the "self" paramter to the super statement).

I'll probably fix it up, no need to drop versions unless it serves a purpose. Thanks!

2021-03-10 06:13 UTC, toumorokoshi approved these changes
Looks good enough, I'll address my comments after merge. Thanks!

2021-03-10 07:09 UTC, merged

2021-03-10 07:14 UTC, toumorokoshi commented
Release in [0.2.1](https://pypi.org/project/deepmerge/). Thanks!

2021-03-10 17:28 UTC, alexreg commented
Thanks, that's great!